### ISSUE TITLE
GH API rate exceeded

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#47]
```
Started by timer
FATAL: Failed to recompute children of go-ipfs
org.jenkinsci.plugins.github_branch_source.RateLimitExceededException: GitHub API rate limit exceeded
	at org.jenkinsci.plugins.github_branch_source.Connector$1.onError(Connector.java:177)
	at org.kohsuke.github.Requester.handleApiError(Requester.java:649)
	at org.kohsuke.github.Requester._to(Requester.java:284)
	at org.kohsuke.github.Requester.to(Requester.java:225)
	at org.kohsuke.github.GitHub.checkApiUrlValidity(GitHub.java:669)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:339)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:148)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:294)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:187)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:139)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Finished: FAILURE
```

**Comment by victorb** [comment]
Hm, interval branch indexing was a temporary solution and we already hit
the limits... What's missing is having an Github account with the right
permissions for setting up hooks. I'll set this up this week.

**Comment by Kubuxu** [comment]
Thank you

**Comment by Kubuxu** [comment]
It also affects builds https://ci.ipfs.team/job/go-ipfs/job/release/2/console
