### ISSUE TITLE
Frequent hangs when building nodejs + windows projects

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#89]
Example: https://ci.ipfs.team/job/IPFS/job/js-ipfs-api/job/PR-678/7/

This job has been running for 3 hr 54 min, and it's stuck on the windows build only.  Could be a issue with aegir as I've seen this happening locally as well.

Thread dump:

```
Thread #4
	at DSL.parallel(Native Method)
	at javascript.call(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:101)
	at DSL.stage(Native Method)
	at javascript.call(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:91)
	at WorkflowScript.run(WorkflowScript:2)
Thread #64
	at DSL.bat(awaiting process completion in c:\jenkins\workspace\IPFS_js-ipfs-api_PR-678-R3GTDVKRFF2AM6ICBPK66O5T7537PK6DGL3G6D6VV5XEZWCU6ZWA@tmp\durable-29e91d2b on JNLP4-connect connection from 52.90.223.49/52.90.223.49:62860; recurrence period: 15000ms; check task scheduled; cancelled? false done? false)
	at javascript.windowsStep(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:33)
	at DSL.wrap(Native Method)
	at javascript.windowsStep(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:25)
	at DSL.withEnv(Native Method)
	at javascript.windowsStep(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:20)
	at DSL.ansiColor(Native Method)
	at javascript.windowsStep(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:20)
	at DSL.node(running on aws-windows-69eb086c)
	at javascript.windowsStep(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:20)
	at javascript.getStep(/efs/jenkins/jobs/IPFS/jobs/js-ipfs-api/branches/PR-678/builds/7/libs/Default/vars/javascript.groovy:81)
```

**Comment by victorb** [comment]
Seems to happen on electron + windows as well. Might be something with the windows workers if we see this happen with a golang job as well.

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#99
