### ISSUE TITLE
EADDRINUSE on macos worker

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#97]
Having an EADDRINUSE error happened before, here's one case:
https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/get-ci-green/37/pipeline/14

```
[FS_js-ipfs-api_get-ci-green-F27XKKY5E6RA6ONRZJ3Q7HHMNHH5DJB4UA7HUYD2FFZMKXYOPBIQ] Running shell script

+ ./node_modules/.bin/yarn test

yarn run v1.5.1

$ aegir test

Test Node.js

listen EADDRINUSE 127.0.0.1:43134

Error: listen EADDRINUSE 127.0.0.1:43134

    at Object._errnoException (util.js:1031:13)

    at _exceptionWithHostPort (util.js:1052:20)

    at Server.setupListenHandle [as _listen2] (net.js:1367:14)

    at listenInCluster (net.js:1408:12)

    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1523:7)

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)

error An unexpected error occurred: "Command failed.

Exit code: 1

Command: sh

Arguments: -c aegir test

Directory: /private/var/jenkins/workspace/FS_js-ipfs-api_get-ci-green-F27XKKY5E6RA6ONRZJ3Q7HHMNHH5DJB4UA7HUYD2FFZMKXYOPBIQ

Output:

".

info If you think this is a bug, please open a bug report with the information provided in "/private/var/jenkins/workspace/FS_js-ipfs-api_get-ci-green-F27XKKY5E6RA6ONRZJ3Q7HHMNHH5DJB4UA7HUYD2FFZMKXYOPBIQ/yarn-error.log".

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vmx** [comment]
It seems to happen on worker macstadium-macos-69e8c913 only.

**Comment by Kubuxu** [comment]
Is js using random port? IIRC form our previous experiences with MacOS on TeamCity, sometimes program instances were not closed after test finished which meant that if static port was used it would be failing.

**Comment by victorb** [comment]
I've turned off the worker for now and will look into the exact cause of npm going missing.

@Kubuxu most tests are using random port but some things are not. Wrote some more about it here: https://github.com/ipfs/js-ipfsd-ctl/pull/212#issuecomment-373472578

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#105
